version: '3'
services:
  api:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - '3000:3000'
    depends_on:
      - db
    networks:
      - app-controle-potreiros
    volumes:
      - ./backend:/app

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - '8080:80'
    networks:
      - app-controle-potreiros
    volumes:
      - ./frontend:/usr/share/nginx/html

  db:
    image: postgres
    ports:
      - '5434:5432'
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    volumes:
      - dbdata:/var/lib/postgresql/data
    networks:
      - app-controle-potreiros

networks:
  app-controle-potreiros:

volumes:
  dbdata: